In [1]:
import torch
import numpy as np

In [2]:

print(torch.__version__)           # Should show 2.5.0+cu124
print(torch.cuda.is_available())   # True
print(torch.version.cuda)          # 12.4 (wheel version)


2.6.0+cu124
True
12.4


In [3]:
data=[[1,2,3],[4,5,6]]

In [4]:
twod_tensor=torch.tensor(data)

In [5]:
#creating tensors of desired shape
shape=(2,3)

In [6]:
ones=torch.ones(shape)
zeros=torch.zeros(shape)
random=torch.rand(shape)

In [7]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
random

tensor([[0.7257, 0.8571, 0.3455],
        [0.5559, 0.4629, 0.5608]])

In [58]:
n=torch.arange(0,100,10)

In [59]:
n

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
#initialize it with np array
np_array=np.arange(12).reshape(3,4)

In [11]:
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
np_array.dtype

dtype('int64')

In [13]:
tensor_from_np=torch.tensor(np_array)

In [14]:
tensor_from_np

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [15]:
tensor_from_np.dtype

torch.int64

In [16]:
ones.dtype

torch.float32

In [17]:
ones.shape

torch.Size([2, 3])

In [18]:
#default device is cpu
ones.device

device(type='cpu')

In [19]:
#setup gpu device if available
device=torch.device("cpu")
if torch.cuda.is_available():
    device=torch.device("cuda") #gpu device
elif torch.backends.mps.is_available():
    device=torch.device("mps")  #mac gpu device
print("Using device:",device)

Using device: cuda


In [20]:
tensor2=torch.tensor([[7,8,9,10],[13,11,12,14],[13,11,12,14]],device='cuda')

In [21]:
tensor2.device

device(type='cuda', index=0)

In [22]:
#* does element wise multiplication with both tensors on the same device
tensor_from_np*tensor2.to('cpu')

tensor([[  0,   8,  18,  30],
        [ 52,  55,  72,  98],
        [104,  99, 120, 154]])

In [23]:
ten3=torch.randint(20,100,(4,2))

In [24]:
ten3

tensor([[87, 45],
        [46, 28],
        [76, 45],
        [28, 98]])

In [ ]:
#3X4 and 4X2 => 3X2; match shape for matrix multiplication
mat_mult=tensor_from_np@ten3.to('cpu')

In [26]:
mat_mult

tensor([[ 282,  412],
        [1230, 1276],
        [2178, 2140]])

In [27]:
#3X4 and 4X2 => 3X2
mat_prod=torch.matmul(tensor_from_np, ten3.to('cpu'))

In [50]:
device

device(type='cuda')

In [53]:
#alternatively you may shift both tensors to gpu if available
mat_prod_gpu=torch.matmul(tensor_from_np.to(device).float(), ten3.to(device).float())

In [28]:
mat_prod.shape

torch.Size([3, 2])

In [29]:
mat_prod

tensor([[ 282,  412],
        [1230, 1276],
        [2178, 2140]])

In [57]:
mat_prod_gpu

tensor([[ 282.,  412.],
        [1230., 1276.],
        [2178., 2140.]], device='cuda:0')

In [54]:
mat_prod_gpu.device

device(type='cuda', index=0)

In [55]:
#numpy works only on cpu, if tensor is on gpu, can't covert to numpy directly
#Move Tensor to CPU first, then convert it to numpy
ten_gpu=mat_prod_gpu.to('cpu').numpy()

In [56]:
ten_gpu

array([[ 282.,  412.],
       [1230., 1276.],
       [2178., 2140.]], dtype=float32)

In [30]:
#reduction operations and dim operator
#default is to reduce all dimensions
ten_sum=tensor_from_np.sum()

In [31]:
ten_sum

tensor(66)

In [32]:
tensor_from_np

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [33]:
#dim=0 collapse rows, get sum of each column
ten_sum_dim0=tensor_from_np.sum(dim=0)

In [34]:
ten_sum_dim0

tensor([12, 15, 18, 21])

In [35]:
#dim=1 collapse columns, get sum of each row
ten_sum_dim1=tensor_from_np.sum(dim=1)

In [36]:
ten_sum_dim1

tensor([ 6, 22, 38])

In [37]:
tensor_from_np

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [38]:
#indexing and slicing
tensor_from_np[:,1]  #all rows, column 1

tensor([1, 5, 9])

In [39]:
tensor_from_np[2,:]  #row 2, all columns

tensor([ 8,  9, 10, 11])

In [40]:
#index of max value in entire tensor
tensor_from_np.argmax()

tensor(11)

In [41]:
#index of max value in column wise
max_index=tensor_from_np.argmax(dim=0)

In [42]:
max_index

tensor([2, 2, 2, 2])

In [43]:
#index of max value in row wise
max_index_r=tensor_from_np.argmax(dim=1)

In [44]:
max_index_r

tensor([3, 3, 3])

In [45]:
#requires_grad=True for gradient tracking
#compute y=a+b, x=y*c
#Only Tensors of floating point and complex dtype can require gradients
a=torch.tensor(4.,requires_grad=True)
b=torch.tensor(3.,requires_grad=True)
c=torch.tensor(2.,requires_grad=True)
y=a+b
x=y*c

In [46]:
x

tensor(14., grad_fn=<MulBackward0>)

In [47]:
#print computation graph of x
#x points back to y and c via multiply operation
x.grad_fn

In [48]:
#print computation graph of y
#y points back to a and b via addition operation
y.grad_fn

In [49]:
a.grad_fn

In [ ]:
#reshaping, stacking, squeezing & unsqueezing tensors
ten_reshaped=tensor_from_np.reshape(4,3) #3X4 to 4X3

In [66]:
ten_reshaped

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [63]:
d=torch.arange(1.,11.)

In [ ]:
d, d.shape #1X10

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [70]:
d_reshaped=d.reshape(10,1)  #10X1

In [109]:
d_reshaped,d_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [55.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [75]:
#change view of tensor without changing data
#view() shares the underlying data memory with original tensor

d_view=d_reshaped.view(1,10)  #1X10

#change in d_view will reflect in d_reshaped as both share same data memory

In [76]:
d_view

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [77]:
d_view[:,5]=55

In [79]:
d_view

tensor([[ 1.,  2.,  3.,  4.,  5., 55.,  7.,  8.,  9., 10.]])

In [78]:
d_reshaped

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [55.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [ ]:
#stacking 1D tensors
t1=torch.tensor([1,2,3,4,5,6])
t2=torch.tensor([7,8,9,10,11,12]) 
stack1=torch.stack([t1,t2]) #by default dim=0

In [93]:
stack1, stack1.shape

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 torch.Size([2, 6]))

In [119]:
stack3=torch.stack([t1,t2],dim=0)

In [120]:
stack3, stack3.shape

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 torch.Size([2, 6]))

In [94]:
stack2=torch.stack([t1,t2],dim=1) #by default dim=0

In [95]:
stack2, stack2.shape

(tensor([[ 1,  7],
         [ 2,  8],
         [ 3,  9],
         [ 4, 10],
         [ 5, 11],
         [ 6, 12]]),
 torch.Size([6, 2]))

In [98]:
#stacking tensors
    
v_stack=torch.vstack([t1,t2])  #stack along new 0th dimension

In [99]:
v_stack, v_stack.shape

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 torch.Size([2, 6]))

In [ ]:
#stacking tensors dim=1
t_stack1=torch.hstack([t1,t2])  #stack 1D arrays horizontally

In [101]:
t_stack1,t_stack1.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [121]:
#Stacking 2D tensors
b1=torch.tensor([[1,2,3],[4,5,6]])
b2=torch.tensor([[7,8,9],[10,11,12]])
stack2d=torch.stack([b1,b2],dim=0)  #stack along new 0th dimension

In [122]:
stack2d, stack2d.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]]),
 torch.Size([2, 2, 3]))

In [126]:
b1,b2

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [124]:
stack2d_1=torch.stack([b1,b2],dim=1)  #stack along new 1th dimension

In [125]:
stack2d_1, stack2d_1.shape

(tensor([[[ 1,  2,  3],
          [ 7,  8,  9]],
 
         [[ 4,  5,  6],
          [10, 11, 12]]]),
 torch.Size([2, 2, 3]))

In [127]:
#2D stacking using h/v stack 
h_stack_2d=torch.hstack([b1,b2])  #stack horizontally
v_stack_2d=torch.vstack([b1,b2])  #stack vertically

In [128]:
h_stack_2d, h_stack_2d.shape

(tensor([[ 1,  2,  3,  7,  8,  9],
         [ 4,  5,  6, 10, 11, 12]]),
 torch.Size([2, 6]))

In [129]:
v_stack_2d, v_stack_2d.shape

(tensor([[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([4, 3]))

In [123]:
d_reshaped,d_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [55.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
#squeeze removes all 1 dimensions 
#removes all single dimensions

d_sqz=d_reshaped.squeeze()


In [115]:
d_sqz,d_sqz.shape

(tensor([ 1.,  2.,  3.,  4.,  5., 55.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [130]:
d_unsqz=d_sqz.unsqueeze(dim=0) #add back 1 dimension at dim=0

In [131]:
d_unsqz,d_unsqz.shape

(tensor([[ 1.,  2.,  3.,  4.,  5., 55.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [136]:
d_unsqz_1=d_sqz.unsqueeze(dim=1) #add back 1 dimension at dim=1

In [137]:
d_unsqz_1, d_unsqz_1.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [55.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [117]:
ten3,ten3.shape

(tensor([[87, 45],
         [46, 28],
         [76, 45],
         [28, 98]]),
 torch.Size([4, 2]))

In [ ]:
#unsqueeze adds a dimension of size 1 at specified position
ten3_usqz=ten3.unsqueeze(dim=0)  #add new dimension at position 0    

In [111]:
ten3_usqz,ten3_usqz.shape

(tensor([[[87, 45],
          [46, 28],
          [76, 45],
          [28, 98]]]),
 torch.Size([1, 4, 2]))

In [112]:
ten3_usqz2=ten3.unsqueeze(dim=1)  #add new dimension at position 1   

In [113]:
ten3_usqz2,ten3_usqz2.shape

(tensor([[[87, 45]],
 
         [[46, 28]],
 
         [[76, 45]],
 
         [[28, 98]]]),
 torch.Size([4, 1, 2]))

In [138]:
x1 = torch.randn(1, 3, 224, 224)


In [139]:
x1[0,1, :, :]  #access channel 1 of the image

tensor([[-0.6499,  1.4643,  1.2120,  ..., -0.2972,  0.1260,  0.7305],
        [ 1.3973, -1.0061,  0.5137,  ..., -0.6167, -0.2704, -1.8100],
        [ 1.5333, -1.2825,  0.4559,  ...,  0.9503, -0.8627,  0.2798],
        ...,
        [ 0.3899,  0.3987,  0.4724,  ..., -0.9799,  0.0881,  0.4214],
        [-2.9983,  1.8998, -0.2578,  ...,  1.1079, -0.9472,  1.1910],
        [-1.6559,  1.2352, -1.1579,  ...,  1.1862,  0.3988, -0.2717]])

In [140]:
x2=torch.randn(224,224,3)

In [143]:
x2[ :, :, 1]  #access channel 1 of the image

tensor([[ 0.5058,  1.8652, -0.8546,  ...,  0.1921,  1.5917,  1.8553],
        [ 0.4779,  0.6794, -2.7938,  ...,  0.8873, -1.3025,  1.2110],
        [-0.2943,  0.4364, -0.1800,  ..., -0.0627, -0.1120,  1.6757],
        ...,
        [-1.0742,  0.4389, -0.4260,  ..., -0.5102,  0.9166, -0.4223],
        [ 0.1430, -1.0787, -1.9942,  ..., -1.3727, -0.9577,  1.4136],
        [ 1.3034,  1.9460,  0.4753,  ..., -0.8464,  0.1137, -0.9394]])

In [144]:
x2_img=x2.permute(2,0,1)  #change to channel first format

In [145]:
x2_img.shape

torch.Size([3, 224, 224])

In [146]:
x2_img[1, :, :]

tensor([[ 0.5058,  1.8652, -0.8546,  ...,  0.1921,  1.5917,  1.8553],
        [ 0.4779,  0.6794, -2.7938,  ...,  0.8873, -1.3025,  1.2110],
        [-0.2943,  0.4364, -0.1800,  ..., -0.0627, -0.1120,  1.6757],
        ...,
        [-1.0742,  0.4389, -0.4260,  ..., -0.5102,  0.9166, -0.4223],
        [ 0.1430, -1.0787, -1.9942,  ..., -1.3727, -0.9577,  1.4136],
        [ 1.3034,  1.9460,  0.4753,  ..., -0.8464,  0.1137, -0.9394]])

In [147]:
x2_img_unsqz=x2_img.unsqueeze(dim=0)  #add batch dimension at dim=0

In [148]:
x2_img_unsqz[0,1, :, : ]

tensor([[ 0.5058,  1.8652, -0.8546,  ...,  0.1921,  1.5917,  1.8553],
        [ 0.4779,  0.6794, -2.7938,  ...,  0.8873, -1.3025,  1.2110],
        [-0.2943,  0.4364, -0.1800,  ..., -0.0627, -0.1120,  1.6757],
        ...,
        [-1.0742,  0.4389, -0.4260,  ..., -0.5102,  0.9166, -0.4223],
        [ 0.1430, -1.0787, -1.9942,  ..., -1.3727, -0.9577,  1.4136],
        [ 1.3034,  1.9460,  0.4753,  ..., -0.8464,  0.1137, -0.9394]])

In [150]:
x2_img_unsqz.shape,x2_img.shape

(torch.Size([1, 3, 224, 224]), torch.Size([3, 224, 224]))