In [4]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [8]:
iris = pd.read_csv('D:\mca_aiml_lab\mca_env\Datasets\Iris.csv')
iris

<>:1: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
<>:1: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
C:\Users\HP\AppData\Local\Temp\ipykernel_16044\1603882206.py:1: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
  iris = pd.read_csv('D:\mca_aiml_lab\mca_env\Datasets\Iris.csv')


,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [9]:
iris.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [10]:
# DataSet info

iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str    
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB


In [11]:
# Statistical Summary

iris.describe()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667
std,43.445368,0.828066,0.433594,1.764420,0.763161
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000


In [12]:
# class Distribution

print(iris['Species'].value_counts())

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64


In [13]:
# Missing Values

print(iris.isnull().sum())

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64


In [15]:
# Remove unnecessary columns

if 'Id' in iris.columns:
    iris = iris.drop(columns=['Id'])

iris


,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


In [16]:
# Encoding (Categorical  -> Numeeric)

iris['Species'] = iris['Species'].astype('category').cat.codes



In [17]:
iris

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [18]:
# Feature and target split

X = iris.drop('Species',axis=1)
Y = iris['Species'].values

X.shape , Y.shape

((150, 4), (150,))

In [19]:
X , Y

(     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
 0              5.1           3.5            1.4           0.2
 1              4.9           3.0            1.4           0.2
 2              4.7           3.2            1.3           0.2
 3              4.6           3.1            1.5           0.2
 4              5.0           3.6            1.4           0.2
 ..             ...           ...            ...           ...
 145            6.7           3.0            5.2           2.3
 146            6.3           2.5            5.0           1.9
 147            6.5           3.0            5.2           2.0
 148            6.2           3.4            5.4           2.3
 149            5.9           3.0            5.1           1.8
 
 [150 rows x 4 columns],
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [20]:
# Normalization

scalar_iris = MinMaxScaler()
X_scaled = scalar_iris.fit_transform(X)

X_scaled

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [22]:
# Train-Test split

X_train, X_test , y_train , y_test = train_test_split(X_scaled,Y,test_size=0.2,random_state=42)

X_train , X_test , y_train , y_test

(array([[0.08333333, 0.66666667, 0.        , 0.04166667],
        [0.38888889, 1.        , 0.08474576, 0.125     ],
        [0.66666667, 0.45833333, 0.57627119, 0.54166667],
        [0.13888889, 0.58333333, 0.10169492, 0.04166667],
        [0.02777778, 0.5       , 0.05084746, 0.04166667],
        [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
        [0.58333333, 0.5       , 0.59322034, 0.58333333],
        [0.25      , 0.625     , 0.08474576, 0.04166667],
        [0.19444444, 0.66666667, 0.06779661, 0.04166667],
        [0.25      , 0.875     , 0.08474576, 0.        ],
        [0.41666667, 0.29166667, 0.69491525, 0.75      ],
        [0.47222222, 0.58333333, 0.59322034, 0.625     ],
        [0.66666667, 0.45833333, 0.62711864, 0.58333333],
        [0.30555556, 0.79166667, 0.05084746, 0.125     ],
        [0.30555556, 0.70833333, 0.08474576, 0.04166667],
        [0.33333333, 0.16666667, 0.45762712, 0.375     ],
        [0.55555556, 0.33333333, 0.69491525, 0.58333333],
        [0.583

In [24]:
# Convert to tensor

X_train = torch.tensor(X_train,dtype=torch.float32)
X_test = torch.tensor(X_test,dtype=torch.float32)
y_train = torch.tensor(y_train,dtype=torch.long)
y_test = torch.tensor(y_test,dtype=torch.long)



C:\Users\HP\AppData\Local\Temp\ipykernel_16044\2476590808.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train = torch.tensor(X_train,dtype=torch.float32)


In [25]:
# Model Definition

class IrisModel(nn.Module):
    def __init__(self):
        super(IrisModel,self).__init__()
        self.linear = nn.Linear(4,3)   # 4 features -> 3 classes

    def forward(self,x):
        return self.linear(x)
    
model = IrisModel()



In [28]:
# Loss & optimizer

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

optimizer  , criterion


(Adam (
 Parameter Group 0
     amsgrad: False
     betas: (0.9, 0.999)
     capturable: False
     decoupled_weight_decay: False
     differentiable: False
     eps: 1e-08
     foreach: None
     fused: None
     lr: 0.01
     maximize: False
     weight_decay: 0
 ),
 CrossEntropyLoss())

In [31]:
# Training 

epochs = 1000

for epochs in range(epochs):
    outputs = model(X_train)
    loss = criterion(outputs, y_train)


    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epochs+1) % 20 == 0:
        print(f"Epoch {epochs+1}, Loss:{loss.item(): .4f}")


Epoch 20, Loss: 0.0471
Epoch 40, Loss: 0.0471
Epoch 60, Loss: 0.0471
Epoch 80, Loss: 0.0471
Epoch 100, Loss: 0.0471
Epoch 120, Loss: 0.0471
Epoch 140, Loss: 0.0471
Epoch 160, Loss: 0.0471
Epoch 180, Loss: 0.0471
Epoch 200, Loss: 0.0470
Epoch 220, Loss: 0.0470
Epoch 240, Loss: 0.0470
Epoch 260, Loss: 0.0470
Epoch 280, Loss: 0.0470
Epoch 300, Loss: 0.0470
Epoch 320, Loss: 0.0470
Epoch 340, Loss: 0.0470
Epoch 360, Loss: 0.0470
Epoch 380, Loss: 0.0470
Epoch 400, Loss: 0.0470
Epoch 420, Loss: 0.0470
Epoch 440, Loss: 0.0470
Epoch 460, Loss: 0.0470
Epoch 480, Loss: 0.0469
Epoch 500, Loss: 0.0469
Epoch 520, Loss: 0.0469
Epoch 540, Loss: 0.0469
Epoch 560, Loss: 0.0469
Epoch 580, Loss: 0.0469
Epoch 600, Loss: 0.0469
Epoch 620, Loss: 0.0469
Epoch 640, Loss: 0.0469
Epoch 660, Loss: 0.0469
Epoch 680, Loss: 0.0469
Epoch 700, Loss: 0.0469
Epoch 720, Loss: 0.0469
Epoch 740, Loss: 0.0469
Epoch 760, Loss: 0.0469
Epoch 780, Loss: 0.0469
Epoch 800, Loss: 0.0469
Epoch 820, Loss: 0.0469
Epoch 840, Loss: 0.0

In [34]:
# Evaluation

with torch.no_grad():
    outputs = model(X_test)
    predicted = torch.max(outputs, 1)[1]

    accuracy = (predicted == y_test).sum().item() / len(y_test)

print("\n------- Predictions --------------")
print(predicted.numpy())

print("\n------- Actual ------------------")
print(y_test.numpy())

print(f"\n Accuracy: {accuracy * 100:.2f}%")


------- Predictions --------------
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

------- Actual ------------------
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

 Accuracy: 100.00%
