In [7]:
import pandas as pd

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I Love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizer = CountVectorizer(ngram_range=(3,3))

X = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("\n BoW Matrics:\n",X.toarray())

Vocabulary: ['is the best' 'pasta is great' 'pizza is the']

 BoW Matrics:
 [[0 0 0]
 [1 0 1]
 [0 0 0]
 [0 1 0]]


In [9]:
from sklearn.feature_extraction.text import TfidfTransformer


documents = [
    "I Love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizer = TfidfTransformer()

X = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("\n BoW Matrics:\n",X.toarray())

ValueError: Expected 2D array, got 1D array instead:
array=['I Love pizza' 'Pizza is the best' 'I love pasta' 'Pasta is great'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.