### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating the NumPy Array

In [2]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
# 2d and 3d
b = np.array([[1,2,3],[4,45,6]])
c = np.array([[[1,2],[4,5]],[[5,6],[7,8]]])
print("2d array:\n",b)
print("\n3d array :\n",c)

2d array:
 [[ 1  2  3]
 [ 4 45  6]]

3d array :
 [[[1 2]
  [4 5]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
np.array([1,0,3],dtype=bool)

array([ True, False,  True])

In [8]:
# np.arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# with reshape
np.arange(1,11).reshape(2,5)
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
# np.ones and np.zeros

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# np.random

np.random.random((3,4))

array([[0.25997476, 0.88928378, 0.98880217, 0.56900324],
       [0.66242649, 0.35227671, 0.99182112, 0.10819767],
       [0.01184991, 0.82446304, 0.38858553, 0.80038091]])

In [18]:
# np.linspace(lower range,upper range,no of items you to generate)


np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [20]:
# np.identity

np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Array Attributes

In [32]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [23]:
# ndim

a3.ndim

3

In [ ]:
# shape
a1.shape
a2.shape
a3.shape     # (how to many 2darray occur,row of 2d,col of 2d array)

(2, 2, 2)

In [27]:
# size
a3.size

8

In [35]:
# itemsize
print(a2.itemsize,"bytes")
print(a1.itemsize,"bytes")   # 4 bytes bcz int32
print(a3.itemsize,"bytes")   # 8 bytes bcz int64 by default 

8 bytes
4 bytes
8 bytes


In [38]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [ ]:
# astype  : to change the dataype
a3.astype(np.int16)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int16)

### Array Operation

In [45]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
# scalar Operation

# arithmetic
a1 ** 2
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [49]:
# relational

a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [50]:
a2 > 12

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
# vector operations
# arithmetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [52]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [54]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

### Array Functions

In [59]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[20., 74., 40.],
       [69., 77., 44.],
       [57., 69., 40.]])

In [63]:
# max/min/sum/prod

print(np.max(a1,axis=1))     # across the row items
print(np.min(a1,axis=0))     # across the column items
print(np.prod(a1))

[74. 77. 69.]
[20. 69. 40.]
2177199053568000.0


In [67]:
# mean/median/std/var

print(np.median(a1,axis=1))
print(np.mean(a1,axis=0))
print(np.std(a1,axis=0))
print(np.var(a1,axis=0))

[40. 69. 57.]
[48.66666667 73.33333333 41.33333333]
[20.85398976  3.29983165  1.88561808]
[434.88888889  10.88888889   3.55555556]


In [68]:
# trigonometric functions
np.sin(a1)

array([[ 0.91294525, -0.98514626,  0.74511316],
       [-0.11478481,  0.99952016,  0.01770193],
       [ 0.43616476, -0.11478481,  0.74511316]])

In [71]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(a2)
print(a3)

np.dot(a2,a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [74]:
# log and exponents

print(np.exp(a1))
print(np.log(a1))

[[4.85165195e+08 1.37338298e+32 2.35385267e+17]
 [9.25378173e+29 2.75851345e+33 1.28516001e+19]
 [5.68572000e+24 9.25378173e+29 2.35385267e+17]]
[[2.99573227 4.30406509 3.68887945]
 [4.2341065  4.34380542 3.78418963]
 [4.04305127 4.2341065  3.68887945]]


In [80]:
# round/floor/cell

print(np.random.random((2,3))*100)
print(np.round(np.random.random((2,3))*100))   # round off the nearest integer
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[93.77784887 67.4439099  26.36074941]
 [56.11172833 91.65742265 72.67177025]]
[[87. 63. 30.]
 [28.  9. 67.]]
[[41. 70.  8.]
 [ 4. 73. 22.]]
[[ 7. 71.  5.]
 [10. 25. 44.]]


### Indexing And Slicing

In [83]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print("1D array :\n",a1,"\n2D array :\n",a2,"\n3D array :\n",a3)

1D array :
 [0 1 2 3 4 5 6 7 8 9] 
2D array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
3D array :
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# Indexing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
print(a1[-1])
a2

9


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
print(a2[1,2])
a3

6


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [92]:
print(a3[1,0,1])

5


In [93]:
print(a3[0,0,0])

0


In [94]:
print(a3[1,1,0])

6


In [96]:
# Slicing

a1[2:5:2]


array([2, 4])

In [97]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a2[0,:]

array([0, 1, 2, 3])

In [99]:
a2[:,2]

array([ 2,  6, 10])

In [101]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [107]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [109]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [111]:
a2[1,::3]

array([4, 7])

In [112]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [115]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [118]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [117]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [120]:
a3[0,1]

array([3, 4, 5])

In [121]:
a3[1,:,1]

array([10, 13, 16])

In [123]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [124]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [ ]:
a1

for i in a1:
    print(i, end=' ')

0123456789

In [129]:
a2
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [130]:
a3

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [131]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [136]:
# reshape

# Transpose

print(a2)
print(np.transpose(a2))

#    OR
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [139]:
# ravel
a2
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Stacking

In [ ]:
# horizontally
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertically
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [147]:
# Horizontal
a4
np.hsplit(a4,4)


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [149]:
# Vertically

np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]