### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [35]:
# Code 
import numpy as np
a = np.random.randint(1,100,15)
a

array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [36]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[54, 20, 81, 63],
       [28, 33, 89, 81],
       [29, 53, 68, 86],
       [55, 16, 75, 99],
       [60, 33,  9, 79],
       [77, 74, 53, 16]], dtype=int32)

In [37]:
np.sort(a)

array([11, 23, 27, 31, 31, 31, 33, 39, 47, 76, 81, 87, 91, 93, 99],
      dtype=int32)

In [38]:
np.sort(b,axis=0)

array([[28, 16,  9, 16],
       [29, 20, 53, 63],
       [54, 33, 68, 79],
       [55, 33, 75, 81],
       [60, 53, 81, 86],
       [77, 74, 89, 99]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [39]:
np.append(a,200)


array([ 31,  31,  11,  31,  23,  81,  93,  33,  91,  87,  47,  27,  99,
        39,  76, 200])

In [40]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[54., 20., 81., 63.,  1.],
       [28., 33., 89., 81.,  1.],
       [29., 53., 68., 86.,  1.],
       [55., 16., 75., 99.,  1.],
       [60., 33.,  9., 79.,  1.],
       [77., 74., 53., 16.,  1.]])

In [41]:
np.append(b,np.random.random((b.shape[0],1)),axis =1)

array([[54.        , 20.        , 81.        , 63.        ,  0.51071849],
       [28.        , 33.        , 89.        , 81.        ,  0.41533386],
       [29.        , 53.        , 68.        , 86.        ,  0.79993286],
       [55.        , 16.        , 75.        , 99.        ,  0.31565807],
       [60.        , 33.        ,  9.        , 79.        ,  0.11784079],
       [77.        , 74.        , 53.        , 16.        ,  0.5103326 ]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [42]:
# code 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [43]:
np.concatenate((c,d),axis=0)   # vstack


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
np.concatenate((c,d),axis=1)   #hstack

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [45]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [46]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [47]:
# code
a.shape

(15,)

In [48]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [49]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [50]:
a

array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [51]:
# Find all indices with value greater than 50
np.where(a>50)

(array([ 5,  6,  8,  9, 12, 14]),)

In [52]:
# replace all values > 50 with 0
# a[np.where(a>50)] = 0
#        OR
np.where(a>50,0,a)


array([31, 31, 11, 31, 23,  0,  0, 33,  0,  0, 47, 27,  0, 39,  0],
      dtype=int32)

In [53]:
# replace all values is even with 0
np.where(a%2==0,0,a)

array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39,  0],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [55]:
a

array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [56]:
print(np.argmax(a))

12


In [57]:
b

array([[54, 20, 81, 63],
       [28, 33, 89, 81],
       [29, 53, 68, 86],
       [55, 16, 75, 99],
       [60, 33,  9, 79],
       [77, 74, 53, 16]], dtype=int32)

In [58]:
print("ColumnWise max element index:",np.argmax(b,axis=0))
print("RowWise max element index:",np.argmax(b,axis=1))

ColumnWise max element index: [5 5 1 3]
RowWise max element index: [2 2 3 3 3 0]


In [ ]:
#  np.argmin

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [59]:
# Cumulative Sum : To add current data into its previous data

a



array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [62]:
np.cumsum(a)


array([ 31,  62,  73, 104, 127, 208, 301, 334, 425, 512, 559, 586, 685,
       724, 800])

In [64]:
np.cumprod(b,axis=0)

array([[         54,          20,          81,          63],
       [       1512,         660,        7209,        5103],
       [      43848,       34980,      490212,      438858],
       [    2411640,      559680,    36765900,    43446942],
       [  144698400,    18469440,   330893100,  3432308418],
       [11141776800,  1366738560, 17537334300, 54916934688]])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [65]:
a

array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [ ]:
print(np.percentile(a,100))
print(np.percentile(a,50))
print(np.percentile(a,0))

# Formula:
# P = (n/N)x100

99.0
39.0
11.0


### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [67]:
a

array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [68]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 2, 5, 1, 0, 0, 1, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [69]:
salary = np.array([10000,20000,40000,35000,60000])
experience = np.array([1,2,4,3,6])

np.corrcoef(salary,experience)

array([[1.        , 0.99324324],
       [0.99324324, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [73]:
a

array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [76]:
items = [10,31,33,40,50,61,70,80,90,100]

a[np.isin(a,items)]

array([31, 31, 31, 33], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [78]:
# code
a

array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [79]:
np.flip(a)

array([76, 39, 99, 27, 47, 87, 91, 33, 93, 81, 23, 31, 11, 31, 31],
      dtype=int32)

In [80]:
b

array([[54, 20, 81, 63],
       [28, 33, 89, 81],
       [29, 53, 68, 86],
       [55, 16, 75, 99],
       [60, 33,  9, 79],
       [77, 74, 53, 16]], dtype=int32)

In [81]:
np.flip(b)

array([[16, 53, 74, 77],
       [79,  9, 33, 60],
       [99, 75, 16, 55],
       [86, 68, 53, 29],
       [81, 89, 33, 28],
       [63, 81, 20, 54]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [82]:
a

array([31, 31, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [ ]:
np.put(a,[0,1],[203,23])   #permently change the items
a

array([203,  23,  11,  31,  23,  81,  93,  33,  91,  87,  47,  27,  99,
        39,  76], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [85]:
a

array([203,  23,  11,  31,  23,  81,  93,  33,  91,  87,  47,  27,  99,
        39,  76], dtype=int32)

In [86]:
np.delete(a,0)   # 0 index items is deleted

array([23, 11, 31, 23, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76],
      dtype=int32)

In [88]:
np.delete(a,[0,2,4])

array([23, 31, 81, 93, 33, 91, 87, 47, 27, 99, 39, 76], dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [89]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [90]:
np.intersect1d(m,n)

array([3, 4, 5])

In [91]:
np.setdiff1d(m,n)

array([1, 2])

In [92]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [94]:
np.in1d(m,1)

AttributeError: module 'numpy' has no attribute 'in1d'

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [95]:
a

array([203,  23,  11,  31,  23,  81,  93,  33,  91,  87,  47,  27,  99,
        39,  76], dtype=int32)

In [96]:
np.clip(a,a_min=25,a_max=75)

array([75, 25, 25, 31, 25, 75, 75, 33, 75, 75, 47, 27, 75, 39, 75],
      dtype=int32)

In [97]:
# np.swapaxes
'''
np.swapaxes
np.confirm
np.count_nonzero
np.tile
np.repeat
np.allclose and equals
'''

'\nnp.swapaxes\nnp.confirm\nnp.count_nonzero\nnp.tile\nnp.repeat\nnp.allclose and equals\n'